# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'self-hosted-runner'

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: BuildImage
    jobs:
      - job: Build
        displayName: BuildImageJob
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              containerRegistry: 'dockerhub'
              repository: 'himanshusarma123/currency_exchange_devops'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              tags: '$(tag)'