trigger:
- main

pool:
  name: self-hosted-runner

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- bash: sudo apt update
- bash: sudo apt install unzip

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'general-purpose-s3-himanshusarma'
    backendAWSKey: 'kubernetes-dev.tfstate'